repos:
-  repo: https://github.com/pre-commit/pre-commit-hooks
   rev: v2.3.0
   hooks:
    -   id: check-yaml
    -   id: check-toml
    -   id: check-json
    -   id: check-xml
    -   id: end-of-file-fixer
    -   id: trailing-whitespace
    -   id: check-added-large-files
        args: [— maxkb=2000]
    -   id: check-merge-conflict
    -   id: check-ast
    -   id: double-quote-string-fixer
-  repo: https://github.com/psf/black
   rev: 22.10.0
   hooks:
    -   id: black
- repo: https://github.com/nbQA-dev/nbQA
  rev: 1.6.3
  hooks:
    - id: nbqa-black
      args: [--line-length=72]
    - id: nbqa-flake8
      args: ["--nbqa-diff"]
    - id: nbqa-pyupgrade
      args: ["--py310-plus"]
    - id: nbqa-isort
      args: [--line-length=72]
